server:
  port: 8080

spring:
  application:
    name: placementgo-backend

  datasource:
    url: jdbc:postgresql://localhost:5432/placementgo
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
gemini:
  api-key : galti se key add na kare yaha per 
  base-url: https://generativelanguage.googleapis.com/v1beta
  model: gemini-2.5-flash
  temperature: 0.2
#will do this later right now only local testing okay bro
  flyway:
    enabled: false
    baseline-on-migrate: true
